//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVGSystemCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Payment
    {
        public string Cust_Payment_ID { get; set; }
        public string Cust_Payment_Type { get; set; }
        public double Cust_Payment_Total_Amt { get; set; }
        public System.DateTime Cust_Payment_Date { get; set; }
        public int Emp_ID { get; set; }
        public int Cust_ID { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
