//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVGSystemCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Customer_Payment = new ObservableListSource<Customer_Payment>();
            this.Sales_Order = new ObservableListSource<Sales_Order>();
        }
    
        public int Cust_ID { get; set; }
        public string Cust_FName { get; set; }
        public string Cust_LName { get; set; }
        public string Cust_Type { get; set; }
        public string Cust_Bussiness_Name { get; set; }
        public string Cust_Email { get; set; }
        public string Cust_Address1 { get; set; }
        public string Cust_Address2 { get; set; }
        public string Cust_Suburb { get; set; }
        public string Cust_City { get; set; }
        public string Cust_Postal_Code { get; set; }
        public string Cust_Contact_No { get; set; }
        public Nullable<double> Cust_Balance { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Customer_Payment> Customer_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Sales_Order> Sales_Order { get; set; }
    }
}
