//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVGSystemCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Order()
        {
            this.Purchase_Item = new HashSet<Purchase_Item>();
        }
    
        public string PO_No { get; set; }
        public System.DateTime PO_Date { get; set; }
        public double PO_Total { get; set; }
        public bool PO_Received_Flag { get; set; }
        public int Emp_ID { get; set; }
        public int Supp_ID { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Item> Purchase_Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
